# Generated by Django 3.1.4 on 2020-12-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_url', models.CharField(max_length=100)),
                ('user_rating', models.CharField(max_length=100)),
                ('user_comment', models.CharField(blank=True, max_length=500)),
                ('user_progress', models.CharField(max_length=100)),
                ('book_logged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
