# Generated by Django 3.1.4 on 2020-12-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
