# Generated by Django 3.1.4 on 2020-12-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20201229_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='book_url',
            field=models.CharField(max_length=500),
        ),
    ]
