# Generated by Django 3.1.4 on 2020-12-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20201229_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user_rating',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
